# PowerShell script to fix the over-replacement issues
Write-Host "Starting precision fixes..." -ForegroundColor Green

# Get all HTML files in the project
$htmlFiles = Get-ChildItem -Path "." -Filter "*.html" -Recurse

foreach ($file in $htmlFiles) {
    Write-Host "Fixing $($file.Name)..." -ForegroundColor Yellow
    
    # Read the file content
    $content = Get-Content $file.FullName -Raw -Encoding UTF8
    
    # Fix JavaScript and technical terms
    $content = $content -replace "unesTXpe", "unescape"
    $content = $content -replace "LoCalBusiness", "LocalBusiness"
    $content = $content -replace "CorpusTXtion", "Corporation"
    $content = $content -replace "deliCate", "delicate"
    $content = $content -replace "dupliCate", "duplicate"
    $content = $content -replace "cerTificate", "certificate"
    $content = $content -replace "indoCate", "indicate"
    $content = $content -replace "communitCate", "communicate"
    $content = $content -replace "loTXte", "locate"
    $content = $content -replace "eduCate", "educate"
    $content = $content -replace "vaCant", "vacant"
    $content = $content -replace "signifiCant", "significant"
    $content = $content -replace "deliCacy", "delicacy"
    $content = $content -replace "advoTXte", "advocate"
    $content = $content -replace "fabriTXte", "fabricate"
    $content = $content -replace "syndiTXte", "syndicate"
    $content = $content -replace "reloTXte", "relocate"
    $content = $content -replace "alloTXte", "allocate"
    $content = $content -replace "physiCal", "physical"
    $content = $content -replace "techniCal", "technical"
    $content = $content -replace "elentriCal", "electrical"
    $content = $content -replace "mechaniCal", "mechanical"
    $content = $content -replace "chemiCal", "chemical"
    $content = $content -replace "identiCal", "identical"
    $content = $content -replace "practiCal", "practical"
    $content = $content -replace "typiCal", "typical"
    $content = $content -replace "classiCal", "classical"
    $content = $content -replace "logiCal", "logical"
    $content = $content -replace "critiCal", "critical"
    $content = $content -replace "vertiCal", "vertical"
    $content = $content -replace "optiCal", "optical"
    $content = $content -replace "tropiCal", "tropical"
    $content = $content -replace "topiCal", "topical"
    $content = $content -replace "mediCal", "medical"
    $content = $content -replace "radiCal", "radical"
    $content = $content -replace "poliTical", "political"
    $content = $content -replace "ethiCal", "ethical"
    $content = $content -replace "mythiCal", "mythical"
    $content = $content -replace "Cartesian", "Cartesian"
    $content = $content -replace "scarcity", "scarcity"
    $content = $content -replace "capacity", "capacity"
    $content = $content -replace "tenacity", "tenacity"
    $content = $content -replace "opacity", "opacity"
    $content = $content -replace "efficacy", "efficacy"
    $content = $content -replace "pharmacy", "pharmacy"
    $content = $content -replace "democracy", "democracy"
    $content = $content -replace "bureaucracy", "bureaucracy"
    $content = $content -replace "aristocracy", "aristocracy"
    $content = $content -replace "theocracy", "theocracy"
    $content = $content -replace "autocracy", "autocracy"
    $content = $content -replace "plutocracy", "plutocracy"
    $content = $content -replace "accuracy", "accuracy"
    $content = $content -replace "currency", "currency"
    $content = $content -replace "emergency", "emergency"
    $content = $content -replace "frequency", "frequency"
    $content = $content -replace "tendency", "tendency"
    $content = $content -replace "dependency", "dependency"
    $content = $content -replace "consistency", "consistency"
    $content = $content -replace "efficiency", "efficiency"
    $content = $content -replace "sufficiency", "sufficiency"
    $content = $content -replace "proficiency", "proficiency"
    $content = $content -replace "deficiency", "deficiency"
    $content = $content -replace "vacancy", "vacancy"
    $content = $content -replace "pregnancy", "pregnancy"
    $content = $content -replace "agency", "agency"
    $content = $content -replace "regency", "regency"
    $content = $content -replace "decency", "decency"
    $content = $content -replace "recency", "recency"
    $content = $content -replace "latency", "latency"
    $content = $content -replace "potency", "potency"
    $content = $content -replace "fluency", "fluency"
    $content = $content -replace "truancy", "truancy"
    $content = $content -replace "buoyancy", "buoyancy"
    $content = $content -replace "elegance", "elegance"
    $content = $content -replace "vigilance", "vigilance"
    $content = $content -replace "brilliance", "brilliance"
    $content = $content -replace "radiance", "radiance"
    $content = $content -replace "variance", "variance"
    $content = $content -replace "fragrance", "fragrance"
    $content = $content -replace "balance", "balance"
    $content = $content -replace "romance", "romance"
    $content = $content -replace "performance", "performance"
    $content = $content -replace "accordance", "accordance"
    $content = $content -replace "importance", "importance"
    $content = $content -replace "guidance", "guidance"
    $content = $content -replace "attendance", "attendance"
    $content = $content -replace "maintenance", "maintenance"
    $content = $content -replace "resistance", "resistance"
    $content = $content -replace "assistance", "assistance"
    $content = $content -replace "persistence", "persistence"
    $content = $content -replace "existence", "existence"
    $content = $content -replace "distance", "distance"
    $content = $content -replace "substance", "substance"
    $content = $content -replace "circumstance", "circumstance"
    $content = $content -replace "advance", "advance"
    $content = $content -replace "finance", "finance"
    $content = $content -replace "enhance", "enhance"
    $content = $content -replace "chance", "chance"
    $content = $content -replace "dance", "dance"
    $content = $content -replace "france", "France"
    $content = $content -replace "glance", "glance"
    $content = $content -replace "lance", "lance"
    $content = $content -replace "rance", "rance"
    $content = $content -replace "stance", "stance"
    $content = $content -replace "trance", "trance"
    
    # Save the updated content back to the file
    $content | Out-File -FilePath $file.FullName -Encoding UTF8 -NoNewline
}

Write-Host "Precision fixes completed!" -ForegroundColor Green
